version: '3.3'

services:
    app:
        user: "node:node"
        build: .
        environment:
          #- REACT_NATIVE_PACKAGER_HOSTNAME=206.189.202.45
          - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.26
          #- REACT_NATIVE_PACKAGER_HOSTNAME=192.168.2.12
          #- REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.126
        ports:  
          - "19000:19000"
          - "19001:19001"
          - "19002:19002"
        expose:
          - "19000"
          - "19001"
          - "19002"
        volumes:
          - .:/home/node/app 
        restart: always  
        tty: true